//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class hang_hoa
    {
        public hang_hoa()
        {
            this.hang_nhap = new HashSet<hang_nhap>();
            this.hang_xuat = new HashSet<hang_xuat>();
        }
    
        public int ma_hang_hoa { get; set; }
        public string ten_hang_hoa { get; set; }
        public int so_luong { get; set; }
        public double don_gia { get; set; }
        public int ma_nha_cung_cap { get; set; }
    
        public virtual nha_cung_cap nha_cung_cap { get; set; }
        public virtual ICollection<hang_nhap> hang_nhap { get; set; }
        public virtual ICollection<hang_xuat> hang_xuat { get; set; }
    }
}
