//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class hang_nhap
    {
        public int ma_nhap { get; set; }
        public System.DateTime ngay_nhap { get; set; }
        public double don_gia { get; set; }
        public int so_luong { get; set; }
        public int ma_hang_hoa { get; set; }
    
        public virtual hang_hoa hang_hoa { get; set; }
    }
}
